STATIONS = [
    "Hyderabad Deccan",
    "Secunderabad Junction",
    "Kacheguda",
    "Begumpet",
    "Lingampalli",
    "Malkajgiri",
    "SSS Nilayam (Prasanthi Nilayam)",
    "Dharmavaram Junction",
    "Anantapur",
    "Guntur Junction"
    "Guntakal Junction",
    "Kazipet Junction",
    "Warangal",
    "Vijayawada Junction",
    "Visakhapatnam",
    "Tirupati",
    "Chennai Central",
    "Bangalore City",
    "Mumbai CST",
    "New Delhi",
    "Kolkata Howrah",
    "Pune Junction"
    "charlapalli",
]

TRAINS = [
    {
        "train_number": "17225",
        "train_name": "Amaravati Express",
        "source": "Hyderabad Deccan",
        "destination": "SSS Nilayam (Prasanthi Nilayam)",
        "departure_time": "21:40",
        "running_days": ["Mon", "Wed", "Fri", "Sun"],
        "base_fare": 450,
    },
    {
        "train_number": "17603",
        "train_name": "Kacheguda SSS Nilayam Express",
        "source": "Kacheguda",
        "destination": "SSS Nilayam (Prasanthi Nilayam)",
        "departure_time": "18:15",
        "running_days": ["Daily"],
        "base_fare": 420,
    },
    {
        "train_number": "12760",
        "train_name": "Charminar Express",
        "source": "Hyderabad Deccan",
        "destination": "Chennai Central",
        "departure_time": "18:30",
        "running_days": ["Daily"],
        "base_fare": 650,
    },
    {
        "train_number": "12759",
        "train_name": "Charminar Express",
        "source": "Chennai Central",
        "destination": "Hyderabad Deccan",
        "departure_time": "19:15",
        "running_days": ["Daily"],
        "base_fare": 650,
    },
    {
        "train_number": "12723",
        "train_name": "Telangana Express",
        "source": "Hyderabad Deccan",
        "destination": "New Delhi",
        "departure_time": "06:40",
        "running_days": ["Daily"],
        "base_fare": 1450,
    },
    {
        "train_number": "12724",
        "train_name": "Telangana Express",
        "source": "New Delhi",
        "destination": "Hyderabad Deccan",
        "departure_time": "22:40",
        "running_days": ["Daily"],
        "base_fare": 1450,
    },
    {
        "train_number": "12707",
        "train_name": "Golconda Express",
        "source": "Hyderabad Deccan",
        "destination": "Vijayawada Junction",
        "departure_time": "06:00",
        "running_days": ["Daily"],
        "base_fare": 380,
    },
    {
        "train_number": "12708",
        "train_name": "Golconda Express",
        "source": "Vijayawada Junction",
        "destination": "Hyderabad Deccan",
        "departure_time": "14:20",
        "running_days": ["Daily"],
        "base_fare": 380,
    },
    {
        "train_number": "12786",
        "train_name": "Kacheguda Vishakapatnam Express",
        "source": "Kacheguda",
        "destination": "Visakhapatnam",
        "departure_time": "20:15",
        "running_days": ["Tue", "Thu", "Sat"],
        "base_fare": 720,
    },
    {
        "train_number": "17015",
        "train_name": "Visakha Express",
        "source": "Secunderabad Junction",
        "destination": "Visakhapatnam",
        "departure_time": "21:00",
        "running_days": ["Daily"],
        "base_fare": 720,
    },
    {
        "train_number": "12734",
        "train_name": "Narayanadri Express",
        "source": "Secunderabad Junction",
        "destination": "Tirupati",
        "departure_time": "18:00",
        "running_days": ["Daily"],
        "base_fare": 560,
    },
    {
        "train_number": "12733",
        "train_name": "Narayanadri Express",
        "source": "Tirupati",
        "destination": "Secunderabad Junction",
        "departure_time": "06:30",
        "running_days": ["Daily"],
        "base_fare": 560,
    },
    {
        "train_number": "12785",
        "train_name": "Kacheguda Tirupati Express",
        "source": "Kacheguda",
        "destination": "Tirupati",
        "departure_time": "17:15",
        "running_days": ["Mon", "Thu", "Sat"],
        "base_fare": 540,
    },
    {
        "train_number": "17604",
        "train_name": "Kacheguda Guntakal Express",
        "source": "Kacheguda",
        "destination": "Guntakal Junction",
        "departure_time": "22:30",
        "running_days": ["Daily"],
        "base_fare": 320,
    },
    {
        "train_number": "12649",
        "train_name": "Kongu Express",
        "source": "Bangalore City",
        "destination": "Guntakal Junction",
        "departure_time": "16:20",
        "running_days": ["Daily"],
        "base_fare": 380,
    },
    {
        "train_number": "16589",
        "train_name": "Rani Chennamma Express",
        "source": "Bangalore City",
        "destination": "Hyderabad Deccan",
        "departure_time": "20:00",
        "running_days": ["Daily"],
        "base_fare": 620,
    },
    {
        "train_number": "16590",
        "train_name": "Rani Chennamma Express",
        "source": "Hyderabad Deccan",
        "destination": "Bangalore City",
        "departure_time": "18:40",
        "running_days": ["Daily"],
        "base_fare": 620,
    },
    {
        "train_number": "12603",
        "train_name": "Hyderabad Bangalore Express",
        "source": "Hyderabad Deccan",
        "destination": "Bangalore City",
        "departure_time": "20:30",
        "running_days": ["Daily"],
        "base_fare": 620,
    },
    {
        "train_number": "22691",
        "train_name": "Rajdhani Express",
        "source": "Secunderabad Junction",
        "destination": "New Delhi",
        "departure_time": "06:00",
        "running_days": ["Mon", "Wed", "Fri"],
        "base_fare": 1950,
    },
    {
        "train_number": "22692",
        "train_name": "Rajdhani Express",
        "source": "New Delhi",
        "destination": "Secunderabad Junction",
        "departure_time": "20:05",
        "running_days": ["Tue", "Thu", "Sun"],
        "base_fare": 1950,
    },
    {
        "train_number": "17032",
        "train_name": "Kazipet Express",
        "source": "Kazipet Junction",
        "destination": "Mumbai CST",
        "departure_time": "12:10",
        "running_days": ["Wed", "Sat"],
        "base_fare": 890,
    },
    {
        "train_number": "12702",
        "train_name": "Hussain Sagar Express",
        "source": "Hyderabad Deccan",
        "destination": "Mumbai CST",
        "departure_time": "09:15",
        "running_days": ["Daily"],
        "base_fare": 890,
    },
    {
        "train_number": "12701",
        "train_name": "Hussain Sagar Express",
        "source": "Mumbai CST",
        "destination": "Hyderabad Deccan",
        "departure_time": "22:10",
        "running_days": ["Daily"],
        "base_fare": 890,
    },
    {
        "train_number": "12262",
        "train_name": "Hyderabad Howrah Duronto",
        "source": "Secunderabad Junction",
        "destination": "Kolkata Howrah",
        "departure_time": "05:35",
        "running_days": ["Tue", "Fri"],
        "base_fare": 1650,
    },
    {
        "train_number": "18646",
        "train_name": "East Coast Express",
        "source": "Kacheguda",
        "destination": "Kolkata Howrah",
        "departure_time": "11:15",
        "running_days": ["Daily"],
        "base_fare": 1650,
    },
    {
        "train_number": "17406",
        "train_name": "Kacheguda Guntur Express",
        "source": "Kacheguda",
        "destination": "Vijayawada Junction",
        "departure_time": "19:45",
        "running_days": ["Daily"],
        "base_fare": 380,
    },
    {
        "train_number": "12591",
        "train_name": "Shramik Express",
        "source": "Warangal",
        "destination": "New Delhi",
        "departure_time": "14:00",
        "running_days": ["Sun"],
        "base_fare": 1320,
    },
    {
        "train_number": "17420",
        "train_name": "Amaravati Express",
        "source": "Warangal",
        "destination": "Bangalore City",
        "departure_time": "16:50",
        "running_days": ["Daily"],
        "base_fare": 580,
    },
    {
        "train_number": "17403",
        "train_name": "Prashanthi Express",
        "source": "Secunderabad Junction",
        "destination": "Dharmavaram Junction",
        "departure_time": "20:15",
        "running_days": ["Daily"],
        "base_fare": 480,
    },
    {
        "train_number": "17404",
        "train_name": "Prashanthi Express",
        "source": "Dharmavaram Junction",
        "destination": "Secunderabad Junction",
        "departure_time": "17:30",
        "running_days": ["Daily"],
        "base_fare": 480,
    },
]

CLASS_MULTIPLIERS = {
    "Sleeper (SL)": 1,
    "AC 3 Tier": 2.5,
    "AC 2 Tier": 3.5,
    "AC First Class": 5,
}
STATION_COORDINATES = {
    "Hyderabad Deccan": {"lat": 17.3924, "lon": 78.4675},
    "Secunderabad Junction": {"lat": 17.4337, "lon": 78.5016},
    "Kacheguda": {"lat": 17.3896, "lon": 78.4998},
    "Begumpet": {"lat": 17.4387, "lon": 78.4586},
    "Lingampalli": {"lat": 17.4933, "lon": 78.3193},
    "Malkajgiri": {"lat": 17.4506, "lon": 78.5289},
    "SSS Nilayam (Prasanthi Nilayam)": {"lat": 14.1611, "lon": 77.7590},
    "Dharmavaram Junction": {"lat": 14.4144, "lon": 77.7181},
    "Anantapur": {"lat": 14.6860, "lon": 77.5950},
    "Guntakal Junction": {"lat": 15.1750, "lon": 77.3670},
    "Guntur Junction": {"lat": 16.3067, "lon": 80.4365},
    "Kazipet Junction": {"lat": 17.9667, "lon": 79.5000},
    "Warangal": {"lat": 17.9732, "lon": 79.6074},
    "Vijayawada Junction": {"lat": 16.5193, "lon": 80.6218},
    "Visakhapatnam": {"lat": 17.7231, "lon": 83.3044},
    "Tirupati": {"lat": 13.6491, "lon": 79.4152},
    "Chennai Central": {"lat": 13.0827, "lon": 80.2750},
    "Bangalore City": {"lat": 12.9784, "lon": 77.5730},
    "Mumbai CST": {"lat": 18.9401, "lon": 72.8352},
    "New Delhi": {"lat": 28.6432, "lon": 77.2197},
    "Kolkata Howrah": {"lat": 22.5830, "lon": 88.3426},
    "Pune Junction": {"lat": 18.5289, "lon": 73.8744},
}